import type { Exercice, JourSemaine } from "@/types";

export const PROGRAMME: Exercice[] = [
  // ───── LUNDI — Pectoraux · Épaules · Triceps ─────
  {
    id: "developpe-couche",
    nom: "Développé couché",
    jour: "lundi",
    seriesCibles: "4 × 6–10",
    repsCibles: "6–10",
    seriesCount: 4,
    repos: "60–90 s",
    technique: "Barre à la poitrine, coudes à 45°, poussée explosive.",
    youtubeUrl: "https://youtube.com/watch?v=TDg8SfY65u4",
    groupeMusculaire: "Pectoraux",
  },
  {
    id: "developpe-incline-halteres",
    nom: "Développé incliné haltères",
    jour: "lundi",
    seriesCibles: "3 × 8–12",
    repsCibles: "8–12",
    seriesCount: 3,
    repos: "60–90 s",
    technique: "Banc incliné 30–45°, descente contrôlée jusqu'aux épaules, poussée verticale.",
    youtubeUrl: "https://youtube.com/watch?v=pKZMNVbfUzQ",
    groupeMusculaire: "Pectoraux",
  },
  {
    id: "elevations-laterales-lundi",
    nom: "Élévations latérales",
    jour: "lundi",
    seriesCibles: "3 × 12–15",
    repsCibles: "12–15",
    seriesCount: 3,
    repos: "45–60 s",
    technique: "Légère flexion des coudes, monter jusqu'à hauteur des épaules.",
    youtubeUrl: "https://youtube.com/watch?v=3VcKaXpzqRo",
    groupeMusculaire: "Épaules / Deltoïde latéral",
  },
  {
    id: "extension-triceps-poulie",
    nom: "Extension triceps poulie",
    jour: "lundi",
    seriesCibles: "3 × 10–15",
    repsCibles: "10–15",
    seriesCount: 3,
    repos: "45–60 s",
    technique: "Coudes fixes le long du corps, extension complète, contraction maximale.",
    youtubeUrl: "https://youtube.com/watch?v=YbS3wB1vYf8",
    groupeMusculaire: "Triceps",
  },
  {
    id: "gainage",
    nom: "Gainage",
    jour: "lundi",
    seriesCibles: "3 × 30–45 s",
    repsCibles: "30–45 s",
    seriesCount: 3,
    repos: "45 s",
    technique: "Position planche, bassin neutre, gainage abdominal maximal.",
    youtubeUrl: "https://youtube.com/watch?v=ASdvN_XEl_c",
    groupeMusculaire: "Abdominaux / Gainage",
  },

  // ───── MARDI — Dos · Biceps ─────
  {
    id: "tirage-vertical",
    nom: "Tirage vertical",
    jour: "mardi",
    seriesCibles: "4 × 8–12",
    repsCibles: "8–12",
    seriesCount: 4,
    repos: "60–90 s",
    technique: "Prise pronation large, tirer vers le sternum, coudes vers les hanches.",
    youtubeUrl: "https://youtube.com/watch?v=SALxEARiMkw",
    groupeMusculaire: "Dos / Grand dorsal",
  },
  {
    id: "rowing-assis-poulie",
    nom: "Rowing assis poulie",
    jour: "mardi",
    seriesCibles: "4 × 8–12",
    repsCibles: "8–12",
    seriesCount: 4,
    repos: "60–90 s",
    technique: "Dos droit, tirer la poignée vers le nombril, serrer les omoplates.",
    youtubeUrl: "https://youtube.com/watch?v=GZbfZ033f74",
    groupeMusculaire: "Dos / Trapèzes",
  },
  {
    id: "rowing-un-bras-haltere",
    nom: "Rowing un bras haltère",
    jour: "mardi",
    seriesCibles: "3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "45–60 s",
    technique: "Appui genou et main sur banc, tirer le coude vers la hanche.",
    youtubeUrl: "https://youtube.com/watch?v=pYcpY20QaE8",
    groupeMusculaire: "Dos / Grand dorsal",
  },
  {
    id: "face-pull",
    nom: "Face pull",
    jour: "mardi",
    seriesCibles: "3 × 12–15",
    repsCibles: "12–15",
    seriesCount: 3,
    repos: "45–60 s",
    technique: "Corde à hauteur des yeux, tirer vers le visage, coudes hauts.",
    youtubeUrl: "https://youtube.com/watch?v=rep-qVOkqgk",
    groupeMusculaire: "Épaules / Deltoïde postérieur",
  },
  {
    id: "curl-biceps",
    nom: "Curl biceps",
    jour: "mardi",
    seriesCibles: "3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "45–60 s",
    technique: "Coudes fixes, montée contrôlée, supination complète en haut.",
    youtubeUrl: "https://youtube.com/watch?v=ykJmrZ5v0Oo",
    groupeMusculaire: "Biceps",
  },

  // ───── MERCREDI — Jambes ─────
  {
    id: "presse-cuisses",
    nom: "Presse à cuisses",
    jour: "mercredi",
    seriesCibles: "4 × 8–12",
    repsCibles: "8–12",
    seriesCount: 4,
    repos: "60–90 s",
    technique: "Pieds à largeur des hanches, descente contrôlée, genoux non verrouillés.",
    youtubeUrl: "https://youtube.com/watch?v=K5n2vg3oZa4",
    groupeMusculaire: "Quadriceps",
  },
  {
    id: "leg-curl",
    nom: "Leg curl",
    jour: "mercredi",
    seriesCibles: "3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "45–60 s",
    technique: "Pointes de pieds vers soi, flexion complète, descente lente.",
    youtubeUrl: "https://youtube.com/watch?v=-4qTgfNiyTc",
    groupeMusculaire: "Ischio-jambiers",
  },
  {
    id: "fentes-marchees",
    nom: "Fentes marchées",
    jour: "mercredi",
    seriesCibles: "3 × 8–10/jambe",
    repsCibles: "8–10",
    seriesCount: 3,
    repos: "45–60 s",
    technique: "Grand pas en avant, genou arrière près du sol, torse droit.",
    youtubeUrl: "https://youtube.com/watch?v=QOVaHwm-Q6U",
    groupeMusculaire: "Quadriceps / Fessiers",
  },
  {
    id: "leg-extension",
    nom: "Leg extension",
    jour: "mercredi",
    seriesCibles: "3 × 12–15",
    repsCibles: "12–15",
    seriesCount: 3,
    repos: "45–60 s",
    technique: "Extension complète, contraction en haut, descente lente.",
    youtubeUrl: "https://youtube.com/watch?v=Yyv2CaqVc4A",
    groupeMusculaire: "Quadriceps",
  },
  {
    id: "mollets",
    nom: "Mollets debout ou assis",
    jour: "mercredi",
    seriesCibles: "3 × 12–20",
    repsCibles: "12–20",
    seriesCount: 3,
    repos: "45 s",
    technique: "Amplitude complète, montée lente, pointe du pied vers le haut.",
    youtubeUrl: "https://youtube.com/watch?v=-qsRtzlref8",
    groupeMusculaire: "Mollets",
  },

  // ───── JEUDI — Épaules · Dos · Bras ─────
  {
    id: "developpe-epaules",
    nom: "Développé épaules",
    jour: "jeudi",
    seriesCibles: "3 × 8–12",
    repsCibles: "8–12",
    seriesCount: 3,
    repos: "60–90 s",
    technique: "Assis, haltères ou barre à hauteur d'épaules, poussée verticale.",
    youtubeUrl: "https://youtube.com/watch?v=qEwKCR5JCog",
    groupeMusculaire: "Épaules / Deltoïde antérieur",
  },
  {
    id: "tirage-vertical-prise-neutre",
    nom: "Tirage vertical prise neutre",
    jour: "jeudi",
    seriesCibles: "3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "60–90 s",
    technique: "Prise neutre serrée, tirer vers le sternum, coudes vers les hanches.",
    youtubeUrl: "https://youtube.com/watch?v=Csm3WxedQAw",
    groupeMusculaire: "Dos / Grand dorsal",
  },
  {
    id: "rowing-assis-machine",
    nom: "Rowing assis machine",
    jour: "jeudi",
    seriesCibles: "3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "45–60 s",
    technique: "Dos droit, tirer les poignées vers la ceinture, serrer les omoplates.",
    youtubeUrl: "https://youtube.com/watch?v=GZbfZ033f74",
    groupeMusculaire: "Dos / Trapèzes",
  },
  {
    id: "elevations-laterales-jeudi",
    nom: "Élévations latérales",
    jour: "jeudi",
    seriesCibles: "2–3 × 12–15",
    repsCibles: "12–15",
    seriesCount: 3,
    repos: "45 s",
    technique: "Légère flexion des coudes, monter jusqu'à hauteur des épaules.",
    youtubeUrl: "https://youtube.com/watch?v=3VcKaXpzqRo",
    groupeMusculaire: "Épaules / Deltoïde latéral",
  },
  {
    id: "curl-marteau",
    nom: "Curl marteau",
    jour: "jeudi",
    seriesCibles: "2–3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "45 s",
    technique: "Prise neutre (marteau), coudes fixes, charge modérée.",
    youtubeUrl: "https://youtube.com/watch?v=zC3nLlEICcs",
    groupeMusculaire: "Biceps / Brachial",
  },
  {
    id: "triceps-corde",
    nom: "Triceps corde",
    jour: "jeudi",
    seriesCibles: "2–3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "45 s",
    technique: "Écarter la corde en bas, contraction maximale des triceps.",
    youtubeUrl: "https://youtube.com/watch?v=vB5OHsJ3EME",
    groupeMusculaire: "Triceps",
  },

  // ───── VENDREDI — Jambes · Abdominaux · Cardio ─────
  {
    id: "presse-cuisses-hack-squat",
    nom: "Presse à cuisses / Hack squat",
    jour: "vendredi",
    seriesCibles: "3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "60–90 s",
    technique: "Pieds à largeur des hanches, descente contrôlée, pousser par les talons.",
    youtubeUrl: "https://youtube.com/watch?v=K5n2vg3oZa4",
    groupeMusculaire: "Quadriceps",
  },
  {
    id: "souleve-de-terre-jambes-tendues",
    nom: "Soulevé de terre jambes tendues",
    jour: "vendredi",
    seriesCibles: "3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "60–90 s",
    technique: "Dos neutre, barre proche des jambes, tension ischio tout au long.",
    youtubeUrl: "https://youtube.com/watch?v=JCXUYuzwNrM",
    groupeMusculaire: "Ischio-jambiers / Lombaires",
  },
  {
    id: "fentes-step-up",
    nom: "Fentes ou step-up",
    jour: "vendredi",
    seriesCibles: "3 × 10/jambe",
    repsCibles: "10",
    seriesCount: 3,
    repos: "45–60 s",
    technique: "Grand pas en avant ou montée sur step, torse droit, contrôle à la descente.",
    youtubeUrl: "https://youtube.com/watch?v=dQqApCGd5Ss",
    groupeMusculaire: "Quadriceps / Fessiers",
  },
  {
    id: "crunch-poulie",
    nom: "Crunch à la poulie",
    jour: "vendredi",
    seriesCibles: "3 × 12–15",
    repsCibles: "12–15",
    seriesCount: 3,
    repos: "45 s",
    technique: "À genoux, corde derrière la tête, fléchir le buste vers le bas.",
    youtubeUrl: "https://youtube.com/watch?v=AV5PmZJIrrw",
    groupeMusculaire: "Abdominaux",
  },
  {
    id: "cardio-intervalles",
    nom: "Cardio intervalles vélo/rameur/tapis",
    jour: "vendredi",
    seriesCibles: "10–15 min",
    repsCibles: "10–15 min",
    seriesCount: 1,
    repos: "-",
    technique: "Intervalles : 30 s effort / 30 s récup, ou HIIT au choix.",
    youtubeUrl: "https://youtube.com/watch?v=1skBf6h2ksI",
    groupeMusculaire: "Cardio",
  },
];

export function getExercicesParJour(jour: JourSemaine): Exercice[] {
  return PROGRAMME.filter((e) => e.jour === jour);
}
