import type { Exercice, JourSemaine } from "@/types";

export const PROGRAMME: Exercice[] = [
  // ───── LUNDI — Pectoraux / Triceps ─────
  {
    id: "developpe-couche",
    nom: "Développé couché",
    jour: "lundi",
    seriesCibles: "4 × 8–10",
    repsCibles: "8–10",
    seriesCount: 4,
    repos: "90 s",
    technique: "Barre à la poitrine, coudes à 45°, poussée explosive.",
    youtubeUrl: "https://www.youtube.com/watch?v=rT7DgCr-3pg",
    groupeMusculaire: "Pectoraux",
  },
  {
    id: "ecarte-halteres-incline",
    nom: "Écarté haltères incliné",
    jour: "lundi",
    seriesCibles: "3 × 12–15",
    repsCibles: "12–15",
    seriesCount: 3,
    repos: "60 s",
    technique: "Banc incliné 30°, descente contrôlée, légère flexion des coudes.",
    youtubeUrl: "https://www.youtube.com/watch?v=QENKPHhQVi4",
    groupeMusculaire: "Pectoraux",
  },
  {
    id: "dips-pectoraux",
    nom: "Dips pectoraux",
    jour: "lundi",
    seriesCibles: "3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "90 s",
    technique: "Buste incliné vers l'avant, descente jusqu'à 90°.",
    youtubeUrl: "https://www.youtube.com/watch?v=2z8JmcrW-As",
    groupeMusculaire: "Pectoraux / Triceps",
  },
  {
    id: "extension-triceps-poulie",
    nom: "Extension triceps poulie haute",
    jour: "lundi",
    seriesCibles: "3 × 12–15",
    repsCibles: "12–15",
    seriesCount: 3,
    repos: "60 s",
    technique: "Coudes fixes le long du corps, extension complète.",
    youtubeUrl: "https://www.youtube.com/watch?v=2-LAMcpzODU",
    groupeMusculaire: "Triceps",
  },
  {
    id: "pushdown-corde",
    nom: "Pushdown corde",
    jour: "lundi",
    seriesCibles: "3 × 12–15",
    repsCibles: "12–15",
    seriesCount: 3,
    repos: "60 s",
    technique: "Écarter la corde en bas, contraction maximale des triceps.",
    youtubeUrl: "https://www.youtube.com/watch?v=kiuVA0gs3EI",
    groupeMusculaire: "Triceps",
  },

  // ───── MARDI — Dos / Biceps ─────
  {
    id: "traction-prise-large",
    nom: "Traction prise large",
    jour: "mardi",
    seriesCibles: "4 × 6–8",
    repsCibles: "6–8",
    seriesCount: 4,
    repos: "120 s",
    technique: "Prise pronation large, menton au-dessus de la barre.",
    youtubeUrl: "https://www.youtube.com/watch?v=eGo4IYlbE5g",
    groupeMusculaire: "Dos / Grand dorsal",
  },
  {
    id: "rowing-haltere",
    nom: "Rowing haltère unilatéral",
    jour: "mardi",
    seriesCibles: "3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "60 s",
    technique: "Appui genou et main sur banc, tirer le coude vers la hanche.",
    youtubeUrl: "https://www.youtube.com/watch?v=pYcpY20QaE8",
    groupeMusculaire: "Dos / Grand dorsal",
  },
  {
    id: "tirage-poulie-haute",
    nom: "Tirage poulie haute prise serrée",
    jour: "mardi",
    seriesCibles: "3 × 12–15",
    repsCibles: "12–15",
    seriesCount: 3,
    repos: "60 s",
    technique: "Prise neutre serrée, tirer vers le sternum, coudes vers les hanches.",
    youtubeUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
    groupeMusculaire: "Dos / Grand dorsal",
  },
  {
    id: "curl-barre",
    nom: "Curl barre",
    jour: "mardi",
    seriesCibles: "3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "60 s",
    technique: "Coudes fixes, montée contrôlée, supination en haut.",
    youtubeUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
    groupeMusculaire: "Biceps",
  },
  {
    id: "curl-marteau",
    nom: "Curl marteau",
    jour: "mardi",
    seriesCibles: "3 × 12–15",
    repsCibles: "12–15",
    seriesCount: 3,
    repos: "60 s",
    technique: "Prise neutre (marteau), coudes fixes, charge modérée.",
    youtubeUrl: "https://www.youtube.com/watch?v=zC3nLlEvin4",
    groupeMusculaire: "Biceps / Brachial",
  },

  // ───── MERCREDI — Épaules / Abdos ─────
  {
    id: "developpe-militaire-halteres",
    nom: "Développé militaire haltères",
    jour: "mercredi",
    seriesCibles: "4 × 10–12",
    repsCibles: "10–12",
    seriesCount: 4,
    repos: "75 s",
    technique: "Assis, haltères à hauteur d'épaules, poussée verticale.",
    youtubeUrl: "https://www.youtube.com/watch?v=HzIiNhHhhtA",
    groupeMusculaire: "Épaules / Deltoïde antérieur",
  },
  {
    id: "elevations-laterales",
    nom: "Élévations latérales",
    jour: "mercredi",
    seriesCibles: "3 × 15–20",
    repsCibles: "15–20",
    seriesCount: 3,
    repos: "45 s",
    technique: "Légère flexion des coudes, monter jusqu'à hauteur épaules.",
    youtubeUrl: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
    groupeMusculaire: "Épaules / Deltoïde latéral",
  },
  {
    id: "oiseau",
    nom: "Oiseau (élévations arrière)",
    jour: "mercredi",
    seriesCibles: "3 × 15–20",
    repsCibles: "15–20",
    seriesCount: 3,
    repos: "45 s",
    technique: "Buste penché, coudes légèrement fléchis, élévation arrière.",
    youtubeUrl: "https://www.youtube.com/watch?v=ttvfGg9d76c",
    groupeMusculaire: "Épaules / Deltoïde postérieur",
  },
  {
    id: "crunch-cable",
    nom: "Crunch câble",
    jour: "mercredi",
    seriesCibles: "3 × 15–20",
    repsCibles: "15–20",
    seriesCount: 3,
    repos: "45 s",
    technique: "À genoux, corde derrière la tête, fléchir le buste vers le bas.",
    youtubeUrl: "https://www.youtube.com/watch?v=_x7sPVzmXY0",
    groupeMusculaire: "Abdominaux",
  },
  {
    id: "planche",
    nom: "Planche (gainage)",
    jour: "mercredi",
    seriesCibles: "3 × 45–60 s",
    repsCibles: "45–60 s",
    seriesCount: 3,
    repos: "60 s",
    technique: "Position planche, bassin neutre, gainage abdominal maximal.",
    youtubeUrl: "https://www.youtube.com/watch?v=pSHjTRCQxIw",
    groupeMusculaire: "Abdominaux / Gainage",
  },

  // ───── JEUDI — Quadriceps / Fessiers ─────
  {
    id: "squat-barre",
    nom: "Squat barre libre",
    jour: "jeudi",
    seriesCibles: "4 × 8–10",
    repsCibles: "8–10",
    seriesCount: 4,
    repos: "120 s",
    technique: "Pieds largeur épaules, descente jusqu'aux cuisses parallèles.",
    youtubeUrl: "https://www.youtube.com/watch?v=ultWZbUMPL8",
    groupeMusculaire: "Quadriceps / Fessiers",
  },
  {
    id: "presse-cuisses",
    nom: "Presse à cuisses",
    jour: "jeudi",
    seriesCibles: "3 × 12–15",
    repsCibles: "12–15",
    seriesCount: 3,
    repos: "90 s",
    technique: "Pieds à largeur hanches, descente contrôlée, genoux non verrouillés.",
    youtubeUrl: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
    groupeMusculaire: "Quadriceps",
  },
  {
    id: "fentes-marchees",
    nom: "Fentes marchées haltères",
    jour: "jeudi",
    seriesCibles: "3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "75 s",
    technique: "Grand pas en avant, genou arrière près du sol, torse droit.",
    youtubeUrl: "https://www.youtube.com/watch?v=L8fvypPrzzs",
    groupeMusculaire: "Quadriceps / Fessiers",
  },
  {
    id: "leg-extension",
    nom: "Leg extension",
    jour: "jeudi",
    seriesCibles: "3 × 15–20",
    repsCibles: "15–20",
    seriesCount: 3,
    repos: "60 s",
    technique: "Extension complète, contraction en haut, descente lente.",
    youtubeUrl: "https://www.youtube.com/watch?v=YyvSfVjQeL0",
    groupeMusculaire: "Quadriceps",
  },
  {
    id: "hip-thrust",
    nom: "Hip thrust barre",
    jour: "jeudi",
    seriesCibles: "4 × 10–12",
    repsCibles: "10–12",
    seriesCount: 4,
    repos: "90 s",
    technique: "Dos sur banc, barre sur hanches, poussée vers le haut, contraction fessiers.",
    youtubeUrl: "https://www.youtube.com/watch?v=SEdqd1n0cvg",
    groupeMusculaire: "Fessiers",
  },

  // ───── VENDREDI — Ischio-jambiers / Mollets ─────
  {
    id: "leg-curl-couche",
    nom: "Leg curl couché",
    jour: "vendredi",
    seriesCibles: "4 × 10–12",
    repsCibles: "10–12",
    seriesCount: 4,
    repos: "75 s",
    technique: "Pointes de pieds vers soi, flexion complète, descente lente.",
    youtubeUrl: "https://www.youtube.com/watch?v=1Tq3QdYUuHs",
    groupeMusculaire: "Ischio-jambiers",
  },
  {
    id: "souleve-de-terre-jr",
    nom: "Soulevé de terre jambes raides",
    jour: "vendredi",
    seriesCibles: "3 × 10–12",
    repsCibles: "10–12",
    seriesCount: 3,
    repos: "90 s",
    technique: "Dos neutre, barre proche des jambes, tension ischio tout au long.",
    youtubeUrl: "https://www.youtube.com/watch?v=1uDiW5--rAE",
    groupeMusculaire: "Ischio-jambiers / Lombaires",
  },
  {
    id: "mollets-presse",
    nom: "Mollets à la presse",
    jour: "vendredi",
    seriesCibles: "4 × 15–20",
    repsCibles: "15–20",
    seriesCount: 4,
    repos: "45 s",
    technique: "Orteils sur le bord de la plateforme, amplitude complète.",
    youtubeUrl: "https://www.youtube.com/watch?v=JbyjNymZOt0",
    groupeMusculaire: "Mollets",
  },
  {
    id: "releve-jambes-suspendu",
    nom: "Relevé de jambes suspendu",
    jour: "vendredi",
    seriesCibles: "3 × 12–15",
    repsCibles: "12–15",
    seriesCount: 3,
    repos: "60 s",
    technique: "Suspendu à une barre, monter les jambes tendues ou fléchies.",
    youtubeUrl: "https://www.youtube.com/watch?v=hdng3Nm1x_E",
    groupeMusculaire: "Abdominaux",
  },
];

export function getExercicesParJour(jour: JourSemaine): Exercice[] {
  return PROGRAMME.filter((e) => e.jour === jour);
}
